#!/usr/bin/env bash
# This checks all for domains and IP and subdomains

display_info() {
	record=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION' | tail -n1 | awk '{print $4}')
	destination=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION' | tail -n1 | awk '{print $5}')
	echo "The subdomain $2 is a $record record and points to $destination"
}

if [ "$#" -eq 1 ];
then
	subdomains=("www" "lb-01" "web-01" "web-02")
	for sub_domain in "${subdomains[@]}"
	do
		display_info "$1" "$sub_domain"
	done
elif [ "$#" -eq 2 ];
then
	display_info "$1" "$2"
fi
