#!/usr/bin/env bash

# Installs Nginx with some configurations

sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'

sudo mkdir -p /etc/nginx/html
echo "Hello World!" > /etc/nginx/html/index.html
echo "Oops! page does not exist" > /etc/nginx/html/404.html

printf %s "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	add_header X-Served-By $HOSTNAME;
	root /etc/nginx/html;
	index index.html;

	try_files $uri $uri/ /404.html;
}" > /etc/nginx/sites-available/default

sudo service nginx restart
