#!/usr/bin/env bash
# This fixes the permissions for user
chmod 644 /etc/nginx/nginx.conf
sed -i "li user nginx;" /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
